spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/db_scholarship
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

